name: Run tests on PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Run tests and linting
        run: |
          npm ci
          {{#unless isRescript}}npm run lint --if-present{{/unless}}{{#if isRescript}}npm run build{{/if}}
          npm test
        env:
          CI: true
