name: Release

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Run tests and linting
        run: |
          npm install
          npm run lint --if-present
          npm test
        env:
          CI: true

      - name: Create release using semantic-release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17.1.1
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0
        env:
          # GITHUB_TOKEN is added automatically by GitHub
          GITHUB_TOKEN: {{{{raw}}}}${{ secrets.GITHUB_TOKEN }}{{{{/raw}}}}
          {{#unless noNpm}}NPM_TOKEN: {{{{raw}}}}${{ secrets.NPM_TOKEN }}{{{{/raw}}}}{{/unless}}

