name: Test and publish Supreme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test and create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: cargo install semantic-release-rust --version 1.0.0-alpha.6

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17.1.1
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/exec@5.0
            @semantic-release/git@9.0
        env:
          # GITHUB_TOKEN is added automatically by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish:
    needs: [test]
    name: Publish for MacOS
    runs-on: ubuntu-latest
    env:
      NAME: supreme-${{ github.ref }}-$TARGET
      TARGET: x86_64-apple-darwin
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
        cargo build --release --locked --target $TARGET
        mkdir "$NAME"
        cp "target/$TARGET/release/supreme" "$NAME/"
        cp README.md "$NAME/"
        tar czvf "$NAME.tar.gz" "$NAME"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "$NAME.tar.gz"
        tag: ${{ github.ref }}
